name: Create vdisk with rootfs

on:
  workflow_dispatch:
    inputs:
      codename:
        description: "Select Ubuntu codename:"
        required: true
        type: string
        default: "noble"
      size:
        description: "Select size of vdisk:"
        required: true
        type: string
        default: "10G"
      noLogs:
        description: "Delete releases,tags,workflowRuns?"
        required: true
        type: string
        default: "false"
  schedule:
    - cron: '0 0 * * 4' # Start every Thursday

permissions:
  contents: write # Give permission to put the release into the repo
  actions: write # Give permission to delete workflow runs

env:
  DEFAULT_CODENAME: noble
  DEFAULT_SIZE: 10G

jobs:
  ClearReleasesTagsWorkflowlogs:
    if: ${{ github.event.inputs.noLogs == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete all releases
        run: |
          gh release list --limit 1000 | awk '{print $1}' | while read tag; do
            echo "Deleting release: $tag"
            gh release delete "$tag" -y || true
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete all tags
        run: |
          git fetch --tags
          git ls-remote --tags origin | awk '{print $2}' | sed 's|refs/tags/||' | while read tag; do
            echo "Deleting tag: $tag"
            git push origin --delete "$tag" || true
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0

  CreateVdiskWithRootfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        run: |
          sudo rm /var/lib/man-db/auto-update
          sudo apt update && sudo apt install debootstrap qemu-kvm -y
          CODENAME="${{ github.event.inputs.codename || env.DEFAULT_CODENAME }}"
          echo "CODENAME=$CODENAME" >> "$GITHUB_ENV"
          SIZE="${{ github.event.inputs.size || env.DEFAULT_SIZE }}"
          echo "SIZE=$SIZE" >> "$GITHUB_ENV"
        shell: bash

      - name: Download rootfs
        id: download
        run: |
          mkdir -p /tmp/kvm-virt/rootfs
          sudo debootstrap --arch=amd64 ${CODENAME} /tmp/kvm-virt/rootfs http://archive.ubuntu.com/ubuntu/
        shell: bash

      - name: Configure rootfs
        id: configure
        run: |
          sudo chroot /tmp/kvm-virt/rootfs /bin/bash -c "echo 'virt' > /etc/hostname"
          sudo chroot /tmp/kvm-virt/rootfs /bin/bash -c "echo '127.0.0.1 localhost virt' > /etc/hosts"
          sudo chroot /tmp/kvm-virt/rootfs /bin/bash -c "echo '/dev/vda1 / ext4 defaults,noatime 0 1' > /etc/fstab"
          sudo chroot /tmp/kvm-virt/rootfs /bin/bash -c "echo 'root:000' | chpasswd"
          sudo chroot /tmp/kvm-virt/rootfs /bin/bash -c "useradd -m -G sudo -s /bin/bash vuser"
          sudo chroot /tmp/kvm-virt/rootfs /bin/bash -c "echo 'vuser ALL=(ALL) ALL' >> /etc/sudoers.d/vuser"
          sudo chroot /tmp/kvm-virt/rootfs /bin/bash -c "chmod 0440 /etc/sudoers.d/vuser"
          sudo chroot /tmp/kvm-virt/rootfs /bin/bash -c "echo 'vuser:000' | chpasswd"
          sudo chroot /tmp/kvm-virt/rootfs /bin/bash -c "passwd -l root"
          echo "[Match]" | sudo tee /tmp/kvm-virt/rootfs/etc/systemd/network/20-ens3.network
          echo "Name=ens3" | sudo tee -a /tmp/kvm-virt/rootfs/etc/systemd/network/20-ens3.network
          echo "" | sudo tee -a /tmp/kvm-virt/rootfs/etc/systemd/network/20-ens3.network
          echo "[Network]" | sudo tee -a /tmp/kvm-virt/rootfs/etc/systemd/network/20-ens3.network
          echo "Address=10.0.2.15/24" | sudo tee -a /tmp/kvm-virt/rootfs/etc/systemd/network/20-ens3.network
          echo "Gateway=10.0.2.2" | sudo tee -a /tmp/kvm-virt/rootfs/etc/systemd/network/20-ens3.network
          echo "DNS=8.8.8.8" | sudo tee -a /tmp/kvm-virt/rootfs/etc/systemd/network/20-ens3.network
          sudo chroot /tmp/kvm-virt/rootfs /bin/bash -c "systemctl enable systemd-networkd && systemctl enable systemd-resolved"
        shell: bash

      - name: Create rootfs.tar
        id: tar
        run: |
          sudo tar -cp -f rootfs.tar -C /tmp/kvm-virt rootfs
        shell: bash

      - name: Create vdisk
        id: vdisk
        run: |
          qemu-img create -f qcow2 /tmp/kvm-virt/disk-template.qcow2 ${SIZE}
          sudo modprobe nbd max_part=8
          sudo qemu-nbd --connect=/dev/nbd0 /tmp/kvm-virt/disk-template.qcow2
          sudo parted /dev/nbd0 mklabel msdos
          sudo parted /dev/nbd0 mkpart primary ext4 1MiB 100%
          sudo mkfs.ext4 /dev/nbd0p1
          sudo mount /dev/nbd0p1 /mnt
          sudo mv /tmp/kvm-virt/rootfs/* /mnt/
          sudo umount /mnt
          sudo qemu-nbd --disconnect /dev/nbd0
          rm -rf /tmp/kvm-virt/rootfs
        shell: bash

      - name: Move final files
        id: move
        run: |
          mv /tmp/kvm-virt/disk-template.qcow2 $PWD/${CODENAME}.qcow2
          mv rootfs.tar ${CODENAME}.tar
        shell: bash

      - name: Create Release Info
        run: |
          echo "Ubuntu codename: ${CODENAME}" > release_body.txt
          echo "Virtual disk size: ${SIZE}" >> release_body.txt
        shell: bash

      - name: Create Git Tag and Release with unique name
        id: vars
        run: |
          echo "tag_name=Rootfs-$(date +'%Y%m%d-%H%M%S'-UTC)" >> "$GITHUB_OUTPUT"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.vars.outputs.tag_name }}
          git push origin ${{ steps.vars.outputs.tag_name }}
        shell: bash

      - name: Upload Release
        uses: softprops/action-gh-release@master
        with:
          files: |
            *.tar
            *.qcow2
          tag_name: ${{ steps.vars.outputs.tag_name }}
          name: ${{ steps.vars.outputs.tag_name }}
          draft: false
          prerelease: false
          body_path: release_body.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
